name = "futmanager-backend"
main = "src/index.ts"
compatibility_date = "2024-01-15"

[env.development.vars]
ENVIRONMENT = "development"
SUPABASE_URL = "your_supabase_project_url"
SUPABASE_ANON_KEY = "your_supabase_anon_key"
SUPABASE_SERVICE_ROLE_KEY = "your_supabase_service_role_key"