name = "futmanager-backend"
main = "src/index.ts"
compatibility_date = "2024-01-15"

[vars]
ENVIRONMENT = "production"

# Sensitive variables should be set as secrets using:
# wrangler secret put SUPABASE_URL
# wrangler secret put SUPABASE_ANON_KEY
# wrangler secret put SUPABASE_SERVICE_ROLE_KEY